version: "3.9"

services:
  gitea_db:
    image: postgres:15
    container_name: gitea_db
    restart: always
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea
      POSTGRES_DB: gitea
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - gitea-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gitea"]
      interval: 10s
      timeout: 5s
      retries: 5

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    depends_on:
      gitea_db:
        condition: service_healthy
    environment:
      - DB_TYPE=postgres
      - DB_HOST=gitea_db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    ports:
      - "3000:3000"
      - "222:22"
    volumes:
      - ./gitea:/data
    networks:
      - gitea-net

networks:
  gitea-net:
    driver: bridge
